### ISSUE TITLE
nb alias picks up zip archive

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/m269-installer#3]
The `nb` alias will use `book-r1.zip` as the folder name if the archive exists. Either make sure the alias opens a folder or add instructions to remove the archive.

**Comment by densnow** [comment]
One possible solution is to use `find` with the `-type d` flag (for directories) e.g.
```bash
NB = "jupyter notebook \$(find $FOLDER -type d -name "book-r*" | sort -r | head -1)/notebooks/M269.ipynb"
```
I Sometimes  use "functions" in my `bashrc` instead of aliases for readability e.g.
```bash
NB() {
    LATEST_BOOK_DIR=$(find $FOLDER -type d -name "book-r*" | sort -r | head -1)
    jupyter notebook "$LATEST_BOOK_DIR/notebooks/M269.ipynb"
}
```
Not sure how the `$FOLDER` variable would be handled this way and of course it would mean further changes in the script when "echoing" into the config file.

**Comment by mwermelinger** [comment]
It's actually not a good idea to directly open the cover notebook. Best to open the dashboard in the student's folder so that they can navigate to where they want, e.g. the TMA01 subfolder.
