### ISSUE TITLE
Windows: comma (and maybe other special chars) in M269 folder file path causes `allowed` alias to fail

### ISSUE THREAD

**Issue by densnow** [dsa-ou/m269-installer#34]
A comma, or possibly other special characters in the M269 file path cause the `allowed` alias to fail. The other aliases are unaffected.

I believe the following will fix the issue:
```diff
$CONFIG_FILE = $Profile.CurrentUserCurrentHost
- $ESC = "```""
$ALIASES = @"
function m269-23j {
    cd '$FOLDER'
    & '$VENV\Scripts\Activate.ps1'
}
function nb {
    Start-process -NoNewWindow jupyter -ArgumentList "notebook"
}
function allowed {
    param(
        [string]`$FilePath
    )

-    python $ESC$FOLDER\allowed.py$ESC -c $ESC$FOLDER\m269.json$ESC `$FilePath
+    python '$FOLDER\allowed.py' -c '$FOLDER\m269.json' `$FilePath
}
"@
```

**Comment by mwermelinger** [comment]
What was the reason you used triple-ticks in the first place? We don't want this fix to (re-)create other issues :-)

**Comment by mwermelinger** [comment]
In particular, does it still work with spaces in the path?

**Comment by densnow** [comment]
I think this issue and fix highlights the need for some kind of testing script(s) so we can make sure some a small fix like this doesn't break the whole thing. Although the cost to create the scripts in the first place is high (they would probably be longer than the install scripts...) and I am sure you are busy enough already. 😀

Maybe something for the future?

**Comment by mwermelinger** [comment]
@ICTSoEasy Back some time ago you added triple-backticks to make the PowerShell `allowed` alias work for path names with spaces. Do you remember why you didn't just use simple quotes? It seems the simple quote works for paths with spaces and commas but the triple-backtick only for spaces. Is it because some paths can have quotes themselves the expanded in the script?

**Comment by ICTSoEasy** [comment]
Yes I think that was the case – there was some reason that simple quotes just wouldn’t work. Similarly with putting them in variables rather than directly in the path, the expansion was causing problems!

Who puts commas in paths? Animals!

From: Michel Wermelinger ***@***.***>
Date: Tuesday, 10 October 2023 at 22:31
To: dsa-ou/m269-installer ***@***.***>
Cc: ICT So Easy ***@***.***>, Mention ***@***.***>
Subject: Re: [dsa-ou/m269-installer] Windows: comma (and maybe other special chars) in M269 folder file path causes `allowed` alias to fail (Issue #34)

@ICTSoEasy<https://github.com/ICTSoEasy> Back some time ago you added triple-backticks to make the PowerShell allowed alias work for path names with spaces. Do you remember why you didn't just use simple quotes? It seems the simple quote works for paths with spaces and commas but the triple-backtick only for spaces. Is it because some paths can have quotes themselves the expanded in the script?

**Comment by mwermelinger** [comment]
@densnow Could you change to double-quotes, test with commas, spaces and single-quotes in the path, and then do a PR? Thanks.

**Comment by densnow** [comment]
@mwermelinger Yes, I will have a look at this over the weekend.

**Comment by densnow** [comment]
Just going to add this link here for future reference regarding quotes etc in powershell [https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3)
